//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::quote_category::Entity")]
    QuoteCategory,
}

impl Related<super::quote_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuoteCategory.def()
    }
}

impl Related<super::quotes::Entity> for Entity {
    fn to() -> RelationDef {
        super::quote_category::Relation::Quotes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::quote_category::Relation::Categories.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
