//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::categories::Entity as Categories;
pub use super::quote_category::Entity as QuoteCategory;
pub use super::quotes::Entity as Quotes;
